swagger: "2.0"
info:
  version: "0.0.1"
  title: Shopping List App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /:
    get:
      description: "Returns all items in the shopping list."
      operationId: "getItems"
      parameters: []
      responses:
        200:
          description: "An array of items"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Item"
      x-swagger-router-controller: "ShoppingListApi"
    post:
      description: "Add a new Item to the shooping list."
      operationId: "addItem"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "item"
        description: "the Item to be added"
        required: true
        schema:
          $ref: "#/definitions/Item"
      responses:
        200:
          description: "Successful Item add"
          schema: 
            $ref: "#/definitions/AddResponse"
      x-swagger-router-controller: "ShoppingListApi"
  /item/{id}:
    get:
      description: "Retrieve an item by id from the shooping list."
      operationId: "getItemById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the item to get"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Item response"
          schema:
            $ref: "#/definitions/Item"
      x-swagger-router-controller: "ShoppingListApi"
    delete:
      description: "Delete a item by Id"
      operationId: "deleteItemById"
      parameters:
      - name: "id"
        in: "path"
        description: "id of the item to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        204:
          description: "item deleted"
      x-swagger-router-controller: "ShoppingListApi"
    put:
      description: "Update a single to by id"
      operationId: "updateItemById"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of the item being updated"
        required: true
        type: "integer"
        format: "int64"
      - name: "updated_item"
        in: "body"
        description: "the updated item"
        required: true
        schema:
          $ref: "#/definitions/Item"
      responses:
        200:
          description: "Item updated"
        400:
          description: "Ups.. something went wrong."
      x-swagger-router-controller: "ShoppingListApi"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Item:
    type: "object"
    properties:
      item_id:
        type: "integer"
        description: "Item id"
      name:
        type: "string"
        description: "Item name"
      created:
        type: "string"
        format: "date-time"
        description: "Item created timestamp"
      type:
        type: "string"
        description: "Item type"
      bought:
        type: "boolean"
        description: "Indicates if the item has been bought or not"
  AddResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        description: "Added item id"
